// Generated by CoffeeScript 1.7.1
(function() {
  var errorLength, errorLower, errorNumber, errorSymbol, errorUpper, getArticle, goodpass, isVowel, needs;

  isVowel = function(char) {
    return char === 'a' || char === 'e' || char === 'i' || char === 'o' || char === 'u';
  };

  getArticle = function(word) {
    if (isVowel(word.charAt(0))) {
      return "an";
    } else {
      return "a";
    }
  };

  needs = function(type, n) {
    return "Must contain " + (getArticle(type)) + " " + type + ", if fewer than " + n + " characters.";
  };

  errorLength = function(n) {
    return "Too short (must be " + n + " characters or more).";
  };

  errorUpper = function(n) {
    return needs("uppercase letter", n, "an");
  };

  errorLower = function(n) {
    return needs("lowercase letter", n);
  };

  errorNumber = function(n) {
    return needs("number", n);
  };

  errorSymbol = function(n) {
    return needs("symbol", n);
  };

  goodpass = function(password, _arg) {
    var hasNoLower, hasNoNumber, hasNoSymbol, hasNoUpper, maxLength, msgs, symbolRegex;
    maxLength = (_arg != null ? _arg : {}).maxLength;
    if (!password) {
      return ['Empty password'];
    }
    if ((maxLength != null) && password.length > maxLength) {
      return ['Password exceeds maximum length.'];
    }
    msgs = [];
    symbolRegex = /[-!$%^&*()_+|~=`{}\[\]:";'<>?,.\/]/g;
    hasNoSymbol = !symbolRegex.test(password);
    hasNoNumber = !/[0-9]/g.test(password);
    hasNoUpper = !/[A-Z]/g.test(password);
    hasNoLower = !/[a-z]/g.test(password);
    if (password.length < 8) {
      msgs.push(errorLength(8));
    } else if (password.length < 12) {
      if (hasNoSymbol) {
        msgs.push(errorSymbol(12));
      }
      if (hasNoNumber) {
        msgs.push(errorNumber(16));
      }
      if (hasNoUpper) {
        msgs.push(errorUpper(20));
      }
      if (hasNoLower) {
        msgs.push(errorLower(20));
      }
    } else if (password.length < 16) {
      if (hasNoNumber) {
        msgs.push(errorNumber(16));
      }
      if (hasNoUpper) {
        msgs.push(errorUpper(20));
      }
      if (hasNoLower) {
        msgs.push(errorLower(20));
      }
    } else if (password.length < 20) {
      if (hasNoUpper) {
        msgs.push(errorUpper(20));
      }
      if (hasNoLower) {
        msgs.push(errorLower(20));
      }
    }
    return msgs;
  };

  module.exports = goodpass;

}).call(this);
